version: "3.1"

services:
    app:
        image: node:18.10.0-buster
        working_dir: /home/node/app
        ports:
            - 3000:3000
            - 24678:24678
            - 3001:3001
        volumes:
            - .:/home/node/app:z
        command: sh -c "npm install && npm run dev -- -o"
        links:
            -   redis:db
        depends_on:
            -   redis
        env_file:
            -   .env

    redis:
        image: redis:7.0
        volumes:
            -   db_data:/data:z
        ports:
            - 6379:6379
        command: >
            --requirepass ${REDIS_PASSWORD}
        env_file:
            -   .env

